version: "3.8"

services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    ports:
      - 7017:27017
    volumes:
      - db:/data/db
  app:
    depends_on:
      - mongodb
    build: ./back-end
    restart: unless-stopped
    ports:
      - 3001:3001
    stdin_open: true
    tty: true

volumes:
  db: